spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/huyuhao?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    initial-size: 10
    max-active: 20
    min-idle: 5
    max-wait: 10000
    filter:
      stat:
        enabled: true
        slow-sql-millis: 1000 #慢sql判断值
        merge-sql: true #合并sql，避免相同sql重复打印
        log-slow-sql: true  #慢sql记录
      wall: #防止sql注入攻击配置
        config:
          multi-statement-allow: true
  #config redis
  redis:
    #host: 127.0.0.1
    #port: 6379
    password: 123456
    database: 0
    lettuce:
      pool:
        min-idle: 5
        max-active: 20
        max-wait: -1
        max-idle: 10
    sentinel:
      nodes:
        - 127.0.0.1:6382
        - 127.0.0.1:6383
        - 127.0.0.1:6384
      master: mymaster
  #config redis
  custom:
    redis:
      password: 123456
      sentinel:
        master: mymaster
        nodes:
          - 127.0.0.1:6382
          - 127.0.0.1:6383
          - 127.0.0.1:6384
mybatis:
  type-aliases-package: com.dm.**.domain
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mapper/**/*Mapper.xml
logging:
  level:
    com.dm.mapper: debug